name: github-pages
on:
  push:
    branches: [master]
jobs:
  main:
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v4
        with: { node-version: lts/*, cache: yarn }
      - name: Build
        run: |
          yarn install
          yarn build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: build
      - uses: actions/deploy-pages@v2
