name: github-pages
on:
  push:
    branches: [master]
jobs:
  main:
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@v3
        with: { node-version: lts/*, cache: yarn }
      - name: Build
        run: |
          yarn install
          yarn build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: build
      - uses: actions/deploy-pages@v2
