name: github-pages
on:
  push:
    branches: [master]
jobs:
  main:
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: oven-sh/setup-bun@v2
      - name: Build
        run: |
          bun install --frozen-lockfile
          bun run build
      - uses: actions/upload-pages-artifact@v5
        with:
          path: dist
      - uses: actions/deploy-pages@v5
